version: '3'
services:
  back:
    image: mlops-back
    ports:
      - "7999-8001:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
  front:
    image: mlops-front
    ports:
      - "8002:80"
    environment:
      - WS_BACK_URL=http://mlops-back:5000